### ISSUE TITLE
Payments fails with 403

### ISSUE THREAD

**Issue by ethicka** [zackhsi/venmo#34]
I got this error: `venmo.payment: ERROR Could not find user @Dashed-Username`. 

After using this command: `venmo pay @Dashed-Username 100 "😀"`

I've paid this (obfuscated) user before successfully on the desktop and iPhone app and I can find them using `venmo search Dashed-Username`.

**Comment by zackhsi** [comment]
Seems this is not just for dashed usernames.

The response code is an [undocumented 403](https://developer.venmo.com/docs/errors).

I will ask around. Thanks for reporting.

**Comment by zackhsi** [comment]
@ethicka should be fixed in `0.10.0`.

**Comment by ethicka** [comment]
@zackhsi Thank you! I'll check it out on my next payment.

**Comment by ethicka** [comment]
@zackhsi OK, I tried pay again, but was not able to process using `@username`. 

I was able to pay using a phone number. However, I got the following error (from the emoji I'm guessing). Payment was verified on venmo.com, though.

### Command
`venmo pay 6105555555 100 "🚤"`

### Error
```
Traceback (most recent call last):
  File "/usr/local/bin/venmo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/venmo/cli.py", line 96, in main
    parse_args()
  File "/usr/local/lib/python2.7/site-packages/venmo/cli.py", line 91, in parse_args
    func(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/venmo/payment.py", line 20, in pay
    _pay_or_charge(user, amount, note)
  File "/usr/local/lib/python2.7/site-packages/venmo/payment.py", line 85, in _pay_or_charge
    .format(**locals()))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

**Comment by zackhsi** [comment]
@ethicka thanks for the update. Can you provide more details for the username? It works for me.

Opened https://github.com/zackhsi/venmo/issues/36 for the emoji issue.
