### ISSUE TITLE
Call on id_from_username(username.lower()) fails

### ISSUE THREAD

**Issue by gseastream** [zackhsi/venmo#43]
https://github.com/zackhsi/venmo/blob/86cfe5d3b2a962d42c90b9d39b5e251c205156d0/venmo/payment.py#L39

Because the line linked above makes the call on `username.lower()`, it looks this call will never return an id for a username that has uppercase letters, because `id_from_username` makes a comparison between the string passed to the function (in this case a lowercase forced string) and the username string returned by venmo. So a function call of `id_from_username('myusername')` for a username that is actually MyUserName will compare MyUserName to myusername and thus return None.

**Comment by zackhsi** [comment]
Can you please provide an example?

**Comment by gseastream** [comment]
```
PS C:\Users\Grant> venmo charge @CMU-ATO 1 "Testing venmo api"
2017-11-26 19:27:39,853 venmo.payment: ERROR Could not find user @CMU-ATO
PS C:\Users\Grant> python
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from venmo.user import id_from_username
>>> id_from_username("CMU-ATO")
'2140101622628352945'
>>> id_from_username("CMU-ATo")
>>> id_from_username("cmu-ato")
```

**Comment by zackhsi** [comment]
Hmm, you are right. I think they changed their API at some point.

Usernames are case insensitively unique (I cannot change my username to cmu-ato), so I will lowercase both sides of the comparison.

Thanks for reporting!

**Comment by gseastream** [comment]
I see that commits were made to the repository that fixes the problem, however I cannot seem to get these updates from a pip upgrade. I even tried running `pip uninstall venmo` and then `pip install venmo` but still experience the bug and the code remains unchanged. Should pip be able to send this update?

**Comment by zackhsi** [comment]
I have published 0.11.0 to pypi.

`pip install venmo==0.11.0`

**Comment by gseastream** [comment]
Got it, upgraded with `pip install -U venmo`. Thanks!

**Comment by zackhsi** [comment]
My pleasure!
